# Generated by Django 2.1.2 on 2018-11-01 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='grupo_app.User'),
        ),
    ]
